runtime: python39
entrypoint: gunicorn -b :$PORT app:application

instance_class: F1

env_variables:
  FLASK_ENV: "production"
  FLASK_APP: "app.py"
  MONGODB_URI: "mongodb+srv://rishab0909:1234@cluster0.7icfipp.mongodb.net/edufuture?retryWrites=true&w=majority&appName=Cluster0"

handlers:
- url: /static
  static_dir: static
  secure: always

- url: /.*
  script: auto
  secure: always
